version: '2'
services:
  nginx-proxy:
    #restart: always
    image: jwilder/nginx-proxy:0.5.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    logging:
      driver: fluentd
      options:
        tag: docker.ngingx-proxy
    environment:
      - TZ=Europe/Helsinki
    depends_on:
      - "fluentd"
  fluentd:
    #restart: always
    image: fluent/fluentd:v0.14.11
    ports:
      - 24224:24224
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf:ro
      - ./fluentd/logs:/fluentd/log
    environment:
      - TZ=Europe/Helsinki
