version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-wp-soivi:
    image: nginx:1.11
    environment:
      - VIRTUAL_HOST=soivi.net
