version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./secrets/certs:/etc/nginx/certs:ro
