version: '2'
services:
  apachephp-lamp-soivi:
    image: php:7.1-apache
    volumes:
      - /docker/www/httpd-lamp-soivi:/var/www/html
      - ./wp.soivi/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - "80:80"
