version: '2'
services:
  kontiomaa-wp-nginx:
    image: nginx:1.11.8
    restart: always
    links:
      - kontiomaa-wp-fpm
      - kontiomaa-wp-mysql
    volumes:
      - ./nginx/sites:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      - VIRTUAL_HOST=samuelkontiomaa.com
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https

  kontiomaa-wp-fpm:
    build: ./nginxphp
    restart: always
    volumes:
      - ./nginx/sites:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - kontiomaa-wp-mysql

  kontiomaa-wp-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysli:/var/lib/mysql
