version: '2'
services:
  soivi-wp-nginx:
    restart: always
    image: nginx:1.11
    environment:
      - VIRTUAL_HOST=soivi.net
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - TZ=Europe/Helsinki
    links:
      - soivi-wp-mysql
      - soivi-wp-fpm
    volumes:
      - /docker/www/soivi-wp-nginx:/usr/share/nginx/html
      - ./secrets/certs:/etc/nginx/certs:ro
      - ./configures/soivi-wp/conf.d:/etc/nginx/conf.d:ro
    logging:
      driver: fluentd
      options:
        tag: docker.soivi-wp-nginx

  soivi-wp-mysql:
    restart: always
    image: mysql:8.0
    volumes:
      - /docker/data/soivi-wp-mysql:/var/lib/mysql
    extends:
      file: ./secrets/soivi.yaml
      service: soivi-wp-mysql
    logging:
      driver: fluentd
      options:
        tag: docker.soivi-wp-mysql
    environment:
      - TZ=Europe/Helsinki

  soivi-wp-fpm:
    restart: always
    build: images/nginxphp
    volumes:
      - /docker/www/soivi-wp-nginx:/usr/share/nginx/html
      - ./configures/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - soivi-wp-mysql
    logging:
      driver: fluentd
      options:
        tag: docker.soivi-wp-fpm
    environment:
      - TZ=Europe/Helsinki

