version: '2'
services:
  soivi-lamp-apachephp:
    build: images/apachephp
    volumes:
      - /docker/www/soivi-lamp-apachephp:/var/www/html
      - ./configures/php.ini:/usr/local/etc/php/php.ini:ro
      - ./configures/soivi-lamp/sites-enabled:/etc/apache2/sites-enabled:ro
      - ./secrets/certs:/etc/apache2/ssl:ro
    links:
      - soivi-lamp-mysql
    environment:
      - VIRTUAL_HOST=site1.soivi.net,datajournalismi.soivi.net,download.soivi.net
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - TZ=Europe/Helsinki
    expose:
      - "443"
    logging:
      driver: fluentd
      options:
        tag: docker.soivi-lamp-apachephp

  soivi-lamp-mysql:
    image: mysql:8.0
    volumes:
      - /docker/data/soivi-lamp-mysql:/var/lib/mysql
    extends:
      file: ./secrets/soivi.yaml
      service: soivi-lamp-mysql
    logging:
      driver: fluentd
      options:
        tag: docker.soivi-lamp-mysql
    environment:
      - TZ=Europe/Helsinki
